version: '3.8'
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb2
        restart: always
        ports:
            - 27019:27019
        volumes:
            - mongodb:/data/db
volumes:
    mongodb:
        driver: local
